"""Academic repository ports (interfaces). Implemented in the infrastructure layer."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from src.domain.academic.entities.batch import Batch
from src.domain.academic.entities.course import Course
from src.domain.academic.entities.department import Department
from src.domain.academic.entities.section import Section
from src.domain.academic.entities.semester import Semester
from src.domain.academic.entities.session import Session


class DepartmentRepository(Protocol):
    """Persistence contract for :class:`Department`."""

    async def get(self, department_id: UUID) -> Department | None: ...
    async def get_by_code(self, code: str) -> Department | None: ...
    async def list_page(self, *, limit: int, offset: int) -> list[Department]: ...
    async def count(self) -> int: ...
    async def add(self, department: Department) -> None: ...
    async def update(self, department: Department) -> None: ...
    async def delete(self, department: Department) -> None: ...


class SessionRepository(Protocol):
    """Persistence contract for :class:`Session`."""

    async def get(self, session_id: UUID) -> Session | None: ...
    async def list_page(
        self, *, limit: int, offset: int, is_current: bool | None = None
    ) -> list[Session]: ...
    async def count(self, *, is_current: bool | None = None) -> int: ...
    async def add(self, session: Session) -> None: ...
    async def update(self, session: Session) -> None: ...
    async def delete(self, session: Session) -> None: ...
    async def set_current(self, session_id: UUID) -> None: ...


class SemesterRepository(Protocol):
    """Persistence contract for :class:`Semester`."""

    async def get(self, semester_id: UUID) -> Semester | None: ...
    async def get_by_session_and_number(self, session_id: UUID, number: int) -> Semester | None: ...
    async def list_page(
        self, *, limit: int, offset: int, session_id: UUID | None = None
    ) -> list[Semester]: ...
    async def count(self, *, session_id: UUID | None = None) -> int: ...
    async def add(self, semester: Semester) -> None: ...
    async def update(self, semester: Semester) -> None: ...
    async def delete(self, semester: Semester) -> None: ...


class BatchRepository(Protocol):
    """Persistence contract for :class:`Batch`."""

    async def get(self, batch_id: UUID) -> Batch | None: ...
    async def get_by_code(self, code: str) -> Batch | None: ...
    async def list_page(
        self,
        *,
        limit: int,
        offset: int,
        session_id: UUID | None = None,
        department_id: UUID | None = None,
    ) -> list[Batch]: ...
    async def count(
        self, *, session_id: UUID | None = None, department_id: UUID | None = None
    ) -> int: ...
    async def add(self, batch: Batch) -> None: ...
    async def update(self, batch: Batch) -> None: ...
    async def delete(self, batch: Batch) -> None: ...


class SectionRepository(Protocol):
    """Persistence contract for :class:`Section`."""

    async def get(self, section_id: UUID) -> Section | None: ...
    async def get_by_batch_and_name(self, batch_id: UUID, name: str) -> Section | None: ...
    async def list_page(
        self, *, limit: int, offset: int, batch_id: UUID | None = None
    ) -> list[Section]: ...
    async def count(self, *, batch_id: UUID | None = None) -> int: ...
    async def list_for_batch(self, batch_id: UUID) -> list[Section]: ...
    async def add(self, section: Section) -> None: ...
    async def update(self, section: Section) -> None: ...
    async def delete(self, section: Section) -> None: ...


class CourseRepository(Protocol):
    """Persistence contract for :class:`Course`."""

    async def get(self, course_id: UUID) -> Course | None: ...
    async def get_by_code(self, code: str) -> Course | None: ...
    async def list_page(
        self,
        *,
        limit: int,
        offset: int,
        department_id: UUID | None = None,
        is_active: bool | None = None,
    ) -> list[Course]: ...
    async def count(
        self, *, department_id: UUID | None = None, is_active: bool | None = None
    ) -> int: ...
    async def add(self, course: Course) -> None: ...
    async def update(self, course: Course) -> None: ...
    async def delete(self, course: Course) -> None: ...
    async def get_prerequisite_ids(self, course_id: UUID) -> set[UUID]: ...
    async def add_prerequisite(self, course_id: UUID, prerequisite_id: UUID) -> None: ...
    async def remove_prerequisite(self, course_id: UUID, prerequisite_id: UUID) -> None: ...
    async def prerequisite_exists(self, course_id: UUID, prerequisite_id: UUID) -> bool: ...
    async def list_prerequisites(self, course_id: UUID) -> list[Course]: ...


__all__ = [
    "BatchRepository",
    "CourseRepository",
    "DepartmentRepository",
    "SectionRepository",
    "SemesterRepository",
    "SessionRepository",
]
