"""Timetable repository ports."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from src.domain.timetable.entities.period import Period
from src.domain.timetable.entities.routine import Routine, RoutineDetail


class PeriodRepository(Protocol):
    """Persistence contract for :class:`Period`."""

    async def get(self, period_id: UUID) -> Period | None: ...
    async def get_by_number(self, period_number: int) -> Period | None: ...
    async def list_page(self, *, limit: int, offset: int) -> list[Period]: ...
    async def count(self) -> int: ...
    async def add(self, period: Period) -> None: ...
    async def update(self, period: Period) -> None: ...
    async def delete(self, period: Period) -> None: ...


class RoutineRepository(Protocol):
    """Persistence contract for :class:`Routine`."""

    async def get(self, routine_id: UUID) -> Routine | None: ...
    async def list_page(self, *, limit: int, offset: int) -> list[Routine]: ...
    async def count(self) -> int: ...
    async def add(self, routine: Routine) -> None: ...
    async def update(self, routine: Routine) -> None: ...
    async def delete(self, routine: Routine) -> None: ...


class RoutineDetailRepository(Protocol):
    """Persistence contract for :class:`RoutineDetail`."""

    async def get(self, detail_id: UUID) -> RoutineDetail | None: ...
    async def list_by_routine(self, routine_id: UUID) -> list[RoutineDetail]: ...
    async def add(self, detail: RoutineDetail) -> None: ...
    async def update(self, detail: RoutineDetail) -> None: ...
    async def delete(self, detail: RoutineDetail) -> None: ...
    async def delete_by_routine(self, routine_id: UUID) -> None: ...


__all__ = ["PeriodRepository", "RoutineRepository", "RoutineDetailRepository"]
